/**
 * Custom code that is injected into the configuration page generated by Clay.
 */
module.exports = function(minified) {	
	var clayConfig = this;
	
	var HOURS_BAR_IDX = 0;
	var MINUTES_BAR_IDX = 1;
	var MONTH_BAR_IDX = 4;
	var DAY_BAR_IDX = 5;
	

	/**
	 * Shows or hides the options for combining hours/minutes or months/days
	 */
	function toggleCombinationOptions() {
		var combineHourMinToggle = clayConfig.getItemById('combineHourMinToggle');
		var combineMonthDayToggle = clayConfig.getItemById('combineMonthDayToggle');
		
		if (this.get()[HOURS_BAR_IDX] && this.get()[MINUTES_BAR_IDX]){
			combineHourMinToggle.show();
		} else {
			combineHourMinToggle.set(false);
			combineHourMinToggle.hide();
		}

		if (this.get()[MONTH_BAR_IDX] && this.get()[DAY_BAR_IDX]){
			combineMonthDayToggle.show();
		} else {
			combineMonthDayToggle.set(false);
			combineMonthDayToggle.hide();
		}
	}	
	
	/* Whenever one of the bars is checked or unchecked, show or hide
	the combination options as needed. */
	clayConfig.on(clayConfig.EVENTS.AFTER_BUILD, function() {
		var barCheckboxesGroup = clayConfig.getItemById("barCheckboxesGroup");
		toggleCombinationOptions.call(barCheckboxesGroup);
		barCheckboxesGroup.on('change', toggleCombinationOptions);
	});
};
